# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
import numpy as np
arr=np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
a = np.ones((2, 5))
a=a.astype(int)
stack=np.vstack((arr_2d,a))
stack

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
stack1=np.hstack((arr_2d,a))
stack1

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
x=arr_2d.flatten()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
x=np.arange(0,15)
arr_2d = np.reshape(x, (5, 3))
y=arr_2d.ravel()
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [19]:
arr_2d = np.reshape(y, (5, 3))
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [21]:
x = np.random.random((5,5))
z=np.square(x)
z

array([[9.99939050e-01, 1.47125465e-02, 3.28570871e-03, 3.54509687e-02,
        1.45828512e-01],
       [8.72057077e-02, 2.01608951e-01, 6.14329664e-05, 5.31997883e-01,
        9.87239993e-02],
       [7.09276456e-01, 2.41360787e-01, 5.78840874e-01, 1.68272020e-01,
        1.38159545e-01],
       [2.50350278e-01, 4.04427349e-02, 2.04701407e-01, 5.14210345e-01,
        7.96908536e-01],
       [1.19944277e-01, 3.71083844e-01, 6.70556241e-01, 9.85489780e-02,
        3.12031883e-04]])

## Question:8

### Create 5x6 an array and find the mean?

In [23]:
x = np.random.random((5,6))
z=np.mean(x)
z

0.4648019098599105

## Question:9

### Find the standard deviation of the previous array in Q8?

In [24]:
c=np.std(x)
c

0.3004694948659362

## Question:10

### Find the median of the previous array in Q8?

In [25]:
m=np.median(x)
m

0.3585906797586662

## Question:11

### Find the transpose of the previous array in Q8?

In [26]:
t=np.transpose(x)
t

array([[0.70961668, 0.10464849, 0.28465749, 0.3668655 , 0.82788234],
       [0.11412733, 0.1627219 , 0.93692816, 0.06534934, 0.54577727],
       [0.85746037, 0.33692227, 0.26180902, 0.77737573, 0.91196299],
       [0.91976437, 0.29341351, 0.18868977, 0.34231809, 0.12926605],
       [0.88675951, 0.39624693, 0.66897551, 0.35031586, 0.0708595 ],
       [0.1404068 , 0.90308476, 0.55212858, 0.20648698, 0.63123621]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [28]:
x = np.random.random((4,4))
trace = np.trace(x)
trace

1.6682958356143678

## Question:13

### Find the determinant of the previous array in Q12?

In [29]:
det = np.linalg.det(x) 
det

0.011511594705257535

## Question:14

### Find the 5th and 95th percentile of an array?

In [34]:
y=np.percentile(x,5,axis=0)
y

array([0.17413693, 0.09959531, 0.06361515, 0.17829233])

In [35]:
y=np.percentile(x,95,axis=0)
y

array([0.78347419, 0.76800268, 0.63593771, 0.6785543 ])

## Question:15

### How to find if a given array has any null values?

In [36]:
null=np.isnan(x)
null

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])